name: Upload Release
description: Uploads a built release file
inputs:
  artifact_name:
    description: Artifact name
    required: true
  aws_key_id:
    description: AWS access key ID
    required: false
  aws_secret_access_key:
    description: AWS secret access key
    required: false
  source:
    description: Source location
    required: false
    default: package
  github_token:
    description: GitHub Token
    required: false

runs:
  using: "composite"
  steps:
    - name: Save artifact
      uses: Wandalen/wretry.action@master
      with:
        action: actions/upload-artifact@v4
        with: |
          name: ${{ inputs.artifact_name }}
          path: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}/${{ inputs.artifact_name }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: us-west-2

    - name: Upload stable build to S3 Bucket
      working-directory: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}
      run: aws s3 cp ${{ inputs.artifact_name }} s3://qgroundcontroltest/builds/${{ github.ref_name }}/${{ inputs.artifact_name }} --acl public-read --region eu-north-1
      shell: bash